import assert from "node:assert/strict";
import { mkdtemp, readFile, readdir, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { test } from "node:test";
import { replaceUtf8FileAtomically, writeNewFileDurably } from "./exact-atomic-file";

test("atomic generated-file replacement persists and reads back the exact UTF-8 wire", async () => {
  const directory = await mkdtemp(path.join(os.tmpdir(), "sbl-exact-atomic-"));
  try {
    const file = path.join(directory, "index.json");
    await writeFile(file, "old\n");
    const wire = `${JSON.stringify({ generatedAt: "2026-07-21T00:00:00.000Z" }, null, 2)}\n`;
    await replaceUtf8FileAtomically(file, wire, 1024);
    assert.equal(await readFile(file, "utf8"), wire);
    assert.deepEqual(await readdir(directory), ["index.json"]);
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
});

test("durable evidence creation is exclusive and never overwrites existing bytes", async () => {
  const directory = await mkdtemp(path.join(os.tmpdir(), "sbl-exact-create-"));
  try {
    const file = path.join(directory, "report.json");
    await writeNewFileDurably(file, "first\n");
    await assert.rejects(() => writeNewFileDurably(file, "second\n"), /EEXIST/);
    assert.equal(await readFile(file, "utf8"), "first\n");
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
});

test("atomic replacement enforces its generated byte ceiling before mutation", async () => {
  const directory = await mkdtemp(path.join(os.tmpdir(), "sbl-exact-limit-"));
  try {
    const file = path.join(directory, "index.json");
    await writeFile(file, "old\n");
    await assert.rejects(() => replaceUtf8FileAtomically(file, "too large", 3), /exceeds its 3-byte limit/);
    assert.equal(await readFile(file, "utf8"), "old\n");
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
});
